// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pokeapi} from '../models';
import {themes} from '../models';

export function GetPokemon(arg1:string):Promise<pokeapi.Pokemon>;

export function GetRandomThemes():Promise<Array<themes.Theme>>;
