// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Answer(arg1, arg2, arg3) {
  return window['go']['main']['App']['Answer'](arg1, arg2, arg3);
}

export function GetPokemon(arg1) {
  return window['go']['main']['App']['GetPokemon'](arg1);
}

export function GetRandomThemes() {
  return window['go']['main']['App']['GetRandomThemes']();
}
