// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {themes} from '../models';
import {service} from '../models';
import {pokeapi} from '../models';

export function Answer(arg1:string,arg2:themes.Theme,arg3:themes.Theme):Promise<service.Result>;

export function GetPokemon(arg1:string):Promise<pokeapi.Pokemon>;

export function GetRandomThemes():Promise<service.GameThemes>;
